name: ci

on:
  # push:
  schedule:
    - cron:  '0 20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      # -
      #   name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Inspect builder
      #   run: |
      #     echo "Name:      ${{ steps.buildx.outputs.name }}"
      #     echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
      #     echo "Status:    ${{ steps.buildx.outputs.status }}"
      #     echo "Flags:     ${{ steps.buildx.outputs.flags }}"
      #     echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install jq ca-certificates curl jq libgpgme11
          SKOPEO_VER=v1.4.1
          sudo curl -fsSL -o /usr/bin/skopeo https://github.com/dyrnq/skopeo-binary/releases/download/${SKOPEO_VER}/skopeo
          sudo chmod +x /usr/bin/skopeo
          skopeo -v && skopeo --help
      - name: Images sync
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |          
          for tag in $(curl -fsSL https://k8s.gcr.io/v2/ingress-nginx/controller/tags/list | jq -r '.tags[]' ); do
            skopeo --insecure-policy copy --all --dest-creds $DOCKER_USERNAME:$DOCKER_PASSWORD docker://k8s.gcr.io/ingress-nginx/controller:$tag docker://docker.io/dyrnq/ingress-nginx-controller:$tag
          done
          skopeo --insecure-policy sync --src yaml --all --dest-creds $DOCKER_USERNAME:$DOCKER_PASSWORD --dest docker sync.yaml docker.io/dyrnq