name: ci

on:
  push:
  schedule:
    - cron:  '0 */8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Images sync
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker run -it --rm --env DOCKER_USERNAME=${DOCKER_USERNAME} --env DOCKER_PASSWORD=${DOCKER_PASSWORD} -v $(pwd)/sync.yaml:/opt/sync.yaml dyrnq/skopeo:1.4.1 bash -c "skopeo --insecure-policy sync --src yaml --all --dest-creds \$DOCKER_USERNAME:\$DOCKER_PASSWORD --dest docker /opt/sync.yaml docker.io/dyrnq"
